title: Mark Fleming Tennis
baseURL: /
params:
  description: Medium inspired blogging theme for Stackbit
  layout_style: grid
  palette: green
  header:
    type: header
    title: Ampersand
    logo_img: images/logo.png
    has_nav: true
    nav_links:
      - type: action
        label: Home
        url: /
        style: link
      - type: action
        label: About
        url: /about
        style: link
      - type: action
        label: Style Guide
        url: /style-guide
        style: link
      - type: action
        label: Contact
        url: /contact
        style: link
  footer:
    subscribe_title: Subscribe for new updates
    subscribe_content: Subscribe to my email newsletter to receive useful articles
      and special offers. This monthly email is sent out on the first of every
      month.
    has_subscribe: true
    social_links:
      - type: action
        label: Twitter
        url: https://twitter.com/
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        label: Instagram
        url: https://www.instagram.com/
        style: icon
        icon_class: fa-instagram
        new_window: true
      - type: action
        label: GitHub
        url: https://github.com/
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        label: LinkedIn
        url: https://www.linkedin.com/
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - type: action
        label: DEV
        url: https://dev.to/
        style: icon
        icon_class: fa-dev
        new_window: true
    subscribe_action: /subscribe-success
    has_social: true
    content: "&copy; All rights reserved."
    links:
      - type: action
        label: Made with Stackbit
        url: https://www.stackbit.com
        style: link
        new_window: true
    type: footer
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
