---
title: Mark Fleming Tennis
baseURL: "/"
params:
  description: Mark Fleming is a USPTA tennis professional in Milwaukee, WI. This blog is dedicated to providing tennis tips, drills, and training to players of all ages and skill levels.
  layout_style: grid
  palette: blue
  header:
    type: header
    title: Mark Fleming Tennis
    logo_img: images/logo.png
    has_nav: true
    nav_links:
    - type: action
      label: Home
      url: "/"
      style: link
    - type: action
      label: About
      url: "/about"
      style: link
    - type: action
      label: Contact
      url: "/contact"
      style: link
  footer:
    type: footer
    content: "&copy; Mark Fleming. All rights reserved."
    links: []
    has_social: false
    social_links:
    - type: action
      label: Twitter
      url: https://twitter.com/
      style: icon
      icon_class: fa-twitter
      new_window: true
    - type: action
      label: Instagram
      url: https://www.instagram.com/
      style: icon
      icon_class: fa-instagram
      new_window: true
    - type: action
      label: GitHub
      url: https://github.com/
      style: icon
      icon_class: fa-github
      new_window: true
    - type: action
      label: LinkedIn
      url: https://www.linkedin.com/
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - type: action
      label: DEV
      url: https://dev.to/
      style: icon
      icon_class: fa-dev
      new_window: true
    has_subscribe: true
    subscribe_title: Subscribe for new updates
    subscribe_content: Subscribe to my email newsletter to receive useful articles
      and special offers. This monthly email is sent out on the first of every month.
    subscribe_action: "/subscribe-success"
taxonomies:
  stub: stub
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
